version: 2
jobs:
  deploy:
    docker:
      - image: brandfolderdocker/circleci-flynntools-base:latest
    steps:
      - checkout
      - run: initialize-flynn.sh production
      - run:
          name: git push
          command: git push production $CIRCLE_SHA1:refs/heads/master
      - run:
          name: set flynn version
          command: flynn env set MSHA=$CIRCLE_SHA1
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          context: flynn-production-credentials
          filters:
            branches:
              only: /master/
